project:
  type: website
  output-dir: "docs"
  
website:
  title: "Kelly Wenqian Chen"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - text: "CV"
        file: CV.qmd



    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/wenqian-chen/
      - icon: google
        href: https://scholar.google.com/citations?user=evjoj8sAAAAJ&hl=en
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

